---
label: Default
hide_body: false
fields:
- name: date
  label: Date
  type: datetime
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: ''
